'use strict';

// Arquivo de seed (para popular um banco de dados vazio) da tabela Projects

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Projects', [
      {
        name: 'Projeto 001',
        id: 1,
        locationId: 1,
        departmentId: 1,
        startDate: '2022-06-01',
        endDate: '2023-01-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 002',
        id: 2,
        locationId: 1,
        departmentId: 1,
        startDate: '2022-06-01',
        endDate: '2023-01-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 003',
        id: 3,
        locationId: 1,
        departmentId: 1,
        startDate: '2022-09-01',
        endDate: '2023-01-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 005',
        id: 4,
        locationId: 1,
        departmentId: 2,
        startDate: '2022-01-14',
        endDate: '2022-12-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 006',
        id: 5,
        locationId: 1,
        departmentId: 3,
        startDate: '2021-10-01',
        endDate: '2022-12-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 007',
        id: 6,
        locationId: 2,
        departmentId: 4,
        startDate: '2022-01-03',
        endDate: '2023-07-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 010',
        id: 7,
        locationId: 2,
        departmentId: 5,
        startDate: '2022-03-01',
        endDate: '2022-12-03',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 011',
        id: 8,
        locationId: 1,
        departmentId: 6,
        startDate: '2021-09-01',
        endDate: '2022-11-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 013',
        id: 9,
        locationId: 2,
        departmentId: 7,
        startDate: '2021-09-13',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 014',
        id: 10,
        locationId: 1,
        departmentId: 8,
        startDate: '2022-05-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 016',
        id: 11,
        locationId: 2,
        departmentId: 5,
        startDate: '2022-08-04',
        endDate: '2022-12-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 020',
        id: 12,
        locationId: 1,
        departmentId: 4,
        startDate: '2022-01-01',
        endDate: '2022-10-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 021',
        id: 13,
        locationId: 1,
        departmentId: 4,
        startDate: '2022-01-01',
        endDate: '2022-10-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 022',
        id: 14,
        locationId: 1,
        departmentId: 9,
        startDate: '2021-01-01',
        endDate: '2022-10-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 024',
        id: 15,
        locationId: 1,
        departmentId: 10,
        startDate: '2022-01-01',
        endDate: '2023-01-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 025',
        id: 16,
        locationId: 1,
        departmentId: 9,
        startDate: '2022-05-01',
        endDate: '2022-09-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 026',
        id: 17,
        locationId: 3,
        departmentId: 11,
        startDate: '2022-02-07',
        endDate: '2022-06-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 027',
        id: 18,
        locationId: 2,
        departmentId: 12,
        startDate: '2022-08-04',
        endDate: '2022-12-16',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 028',
        id: 19,
        locationId: 1,
        departmentId: 13,
        startDate: '2021-08-02',
        endDate: '2022-11-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 030',
        id: 20,
        locationId: 1,
        departmentId: 14,
        startDate: '2022-03-01',
        endDate: '2022-09-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 031',
        id: 21,
        locationId: 1,
        departmentId: 6,
        startDate: '2022-05-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 032',
        id: 22,
        locationId: 3,
        departmentId: 11,
        startDate: '2021-09-01',
        endDate: '2022-01-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 035',
        id: 23,
        locationId: 1,
        departmentId: 4,
        startDate: '2022-01-01',
        endDate: '2022-08-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 036',
        id: 24,
        locationId: 1,
        departmentId: 15,
        startDate: '2022-02-01',
        endDate: '2022-12-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 037',
        id: 25,
        locationId: 1,
        departmentId: 9,
        startDate: '2022-05-01',
        endDate: '2023-01-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 039',
        id: 26,
        locationId: 1,
        departmentId: 15,
        startDate: '2021-11-01',
        endDate: '2023-08-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 041',
        id: 27,
        locationId: 1,
        departmentId: 14,
        startDate: '2022-01-01',
        endDate: '2022-08-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 042',
        id: 28,
        locationId: 1,
        departmentId: 10,
        startDate: '2021-09-01',
        endDate: '2022-04-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 043',
        id: 29,
        locationId: 1,
        departmentId: 16,
        startDate: '2022-05-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 044',
        id: 30,
        locationId: 1,
        departmentId: 2,
        startDate: '2022-01-01',
        endDate: '2022-12-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 045',
        id: 31,
        locationId: 1,
        departmentId: 2,
        startDate: '2022-06-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 048',
        id: 32,
        locationId: 1,
        departmentId: 17,
        startDate: '2021-09-01',
        endDate: '2022-08-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 049',
        id: 33,
        locationId: 1,
        departmentId: 18,
        startDate: '2022-01-01',
        endDate: '2022-09-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 050',
        id: 34,
        locationId: 2,
        departmentId: 7,
        startDate: '2022-01-01',
        endDate: '2022-07-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 051',
        id: 35,
        locationId: 3,
        departmentId: 18,
        startDate: '2021-09-01',
        endDate: '2022-07-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 052',
        id: 36,
        locationId: 1,
        departmentId: 6,
        startDate: '2021-01-03',
        endDate: '2022-12-12',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 053',
        id: 37,
        locationId: 1,
        departmentId: 19,
        startDate: '2022-06-01',
        endDate: '2022-12-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 054',
        id: 38,
        locationId: 3,
        departmentId: 6,
        startDate: '2022-01-01',
        endDate: '2022-07-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 055',
        id: 39,
        locationId: 2,
        departmentId: 5,
        startDate: '2021-09-01',
        endDate: '2022-04-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 056',
        id: 40,
        locationId: 2,
        departmentId: 9,
        startDate: '2022-05-01',
        endDate: '2022-10-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 057',
        id: 41,
        locationId: 2,
        departmentId: 11,
        startDate: '2021-09-01',
        endDate: '2022-12-31',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 058',
        id: 42,
        locationId: 1,
        departmentId: 14,
        startDate: '2022-03-01',
        endDate: '2022-08-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 059',
        id: 43,
        locationId: 1,
        departmentId: 18,
        startDate: '2022-01-01',
        endDate: '2022-07-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 061',
        id: 44,
        locationId: 3,
        departmentId: 11,
        startDate: '2021-09-20',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 062',
        id: 45,
        locationId: 3,
        departmentId: 20,
        startDate: '2021-09-14',
        endDate: '2022-12-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 064',
        id: 46,
        locationId: 3,
        departmentId: 3,
        startDate: '2020-09-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 066',
        id: 47,
        locationId: 1,
        departmentId: 11,
        startDate: '2022-01-10',
        endDate: '2022-12-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 071',
        id: 48,
        locationId: 1,
        departmentId: 2,
        startDate: '2022-01-01',
        endDate: '2022-09-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 073',
        id: 49,
        locationId: 3,
        departmentId: 21,
        startDate: '2021-12-28',
        endDate: '2022-06-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 074',
        id: 50,
        locationId: 1,
        departmentId: 9,
        startDate: '2021-09-01',
        endDate: '2022-07-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 075',
        id: 51,
        locationId: 1,
        departmentId: 3,
        startDate: '2022-05-01',
        endDate: '2022-09-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 077',
        id: 52,
        locationId: 1,
        departmentId: 19,
        startDate: '2021-09-13',
        endDate: '2022-09-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 079',
        id: 53,
        locationId: 1,
        departmentId: 11,
        startDate: '2022-01-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 080',
        id: 54,
        locationId: 2,
        departmentId: 7,
        startDate: '2021-09-08',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 081',
        id: 55,
        locationId: 2,
        departmentId: 22,
        startDate: '2020-09-01',
        endDate: '2023-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 082',
        id: 56,
        locationId: 2,
        departmentId: 5,
        startDate: '2021-09-11',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 083',
        id: 57,
        locationId: 1,
        departmentId: 14,
        startDate: '2022-01-01',
        endDate: '2022-05-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 087',
        id: 58,
        locationId: 1,
        departmentId: 9,
        startDate: '2022-01-01',
        endDate: '2022-09-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 089',
        id: 59,
        locationId: 1,
        departmentId: 23,
        startDate: '2021-09-02',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 091',
        id: 60,
        locationId: 2,
        departmentId: 14,
        startDate: '2022-07-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 094',
        id: 61,
        locationId: 2,
        departmentId: 5,
        startDate: '2022-01-01',
        endDate: '2022-07-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 095',
        id: 62,
        locationId: 2,
        departmentId: 24,
        startDate: '2022-07-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 097',
        id: 63,
        locationId: 1,
        departmentId: 3,
        startDate: '2022-06-01',
        endDate: '2022-12-31',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 098',
        id: 64,
        locationId: 1,
        departmentId: 11,
        startDate: '2022-01-01',
        endDate: '2022-06-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 099',
        id: 65,
        locationId: 3,
        departmentId: 3,
        startDate: '2022-07-30',
        endDate: '2022-12-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 100',
        id: 66,
        locationId: 1,
        departmentId: 25,
        startDate: '2021-11-12',
        endDate: '2022-07-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 101',
        id: 67,
        locationId: 1,
        departmentId: 14,
        startDate: '2021-09-14',
        endDate: '2023-07-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 102',
        id: 68,
        locationId: 1,
        departmentId: 14,
        startDate: '2022-01-01',
        endDate: '2022-08-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 103',
        id: 69,
        locationId: 2,
        departmentId: 18,
        startDate: '2022-08-30',
        endDate: '2022-12-31',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 105',
        id: 70,
        locationId: 1,
        departmentId: 4,
        startDate: '2022-10-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 109',
        id: 71,
        locationId: 1,
        departmentId: 14,
        startDate: '2022-01-01',
        endDate: '2022-06-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 110',
        id: 72,
        locationId: 2,
        departmentId: 14,
        startDate: '2022-02-01',
        endDate: '2022-07-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 111',
        id: 73,
        locationId: 1,
        departmentId: 14,
        startDate: '2022-01-01',
        endDate: '2022-06-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 112',
        id: 74,
        locationId: 2,
        departmentId: 14,
        startDate: '2022-08-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 113',
        id: 75,
        locationId: 1,
        departmentId: 14,
        startDate: '2022-08-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 115',
        id: 76,
        locationId: 1,
        departmentId: 18,
        startDate: '2022-01-01',
        endDate: '2022-12-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Projects', null, {});
  },
};
