'use strict';

// Arquivo de seed (para popular um banco de dados vazio) da tabela Projects

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Projects', [
      {
        name: 'Projeto 001',
        locationId: 1,
        departmentId: 1,
        startDate: '2022-06-01',
        endDate: '2023-01-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 002',
        locationId: 1,
        departmentId: 1,
        startDate: '2022-06-01',
        endDate: '2023-01-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 003',
        locationId: 1,
        departmentId: 1,
        startDate: '2022-09-01',
        endDate: '2023-01-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 005',
        locationId: 1,
        departmentId: 2,
        startDate: '2022-01-14',
        endDate: '2022-12-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 006',
        locationId: 1,
        departmentId: 3,
        startDate: '2021-10-01',
        endDate: '2022-12-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 007',
        locationId: 2,
        departmentId: 4,
        startDate: '2022-01-03',
        endDate: '2023-07-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 010',
        locationId: 2,
        departmentId: 5,
        startDate: '2022-03-01',
        endDate: '2022-12-03',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 011',
        locationId: 1,
        departmentId: 6,
        startDate: '2021-09-01',
        endDate: '2022-11-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 013',
        locationId: 2,
        departmentId: 7,
        startDate: '2021-09-13',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 014',
        locationId: 1,
        departmentId: 8,
        startDate: '2022-05-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 016',
        locationId: 2,
        departmentId: 5,
        startDate: '2022-08-04',
        endDate: '2022-12-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 020',
        locationId: 1,
        departmentId: 4,
        startDate: '2022-01-01',
        endDate: '2022-10-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 021',
        locationId: 1,
        departmentId: 4,
        startDate: '2022-01-01',
        endDate: '2022-10-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 022',
        locationId: 1,
        departmentId: 9,
        startDate: '2021-01-01',
        endDate: '2022-10-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 024',
        locationId: 1,
        departmentId: 10,
        startDate: '2022-01-01',
        endDate: '2023-01-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 025',
        locationId: 1,
        departmentId: 9,
        startDate: '2022-05-01',
        endDate: '2022-09-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 026',
        locationId: 3,
        departmentId: 11,
        startDate: '2022-02-07',
        endDate: '2022-06-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 027',
        locationId: 2,
        departmentId: 12,
        startDate: '2022-08-04',
        endDate: '2022-12-16',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 028',
        locationId: 1,
        departmentId: 13,
        startDate: '2021-08-02',
        endDate: '2022-11-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 030',
        locationId: 1,
        departmentId: 14,
        startDate: '2022-03-01',
        endDate: '2022-09-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 031',
        locationId: 1,
        departmentId: 6,
        startDate: '2022-05-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 032',
        locationId: 3,
        departmentId: 11,
        startDate: '2021-09-01',
        endDate: '2022-01-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 035',
        locationId: 1,
        departmentId: 4,
        startDate: '2022-01-01',
        endDate: '2022-08-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 036',
        locationId: 1,
        departmentId: 15,
        startDate: '2022-02-01',
        endDate: '2022-12-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 037',
        locationId: 1,
        departmentId: 9,
        startDate: '2022-05-01',
        endDate: '2023-01-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 039',
        locationId: 1,
        departmentId: 15,
        startDate: '2021-11-01',
        endDate: '2023-08-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 041',
        locationId: 1,
        departmentId: 14,
        startDate: '2022-01-01',
        endDate: '2022-08-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 042',
        locationId: 1,
        departmentId: 10,
        startDate: '2021-09-01',
        endDate: '2022-04-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 043',
        locationId: 1,
        departmentId: 16,
        startDate: '2022-05-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 044',
        locationId: 1,
        departmentId: 2,
        startDate: '2022-01-01',
        endDate: '2022-12-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 045',
        locationId: 1,
        departmentId: 2,
        startDate: '2022-06-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 048',
        locationId: 1,
        departmentId: 17,
        startDate: '2021-09-01',
        endDate: '2022-08-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 049',
        locationId: 1,
        departmentId: 18,
        startDate: '2022-01-01',
        endDate: '2022-09-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 050',
        locationId: 2,
        departmentId: 7,
        startDate: '2022-01-01',
        endDate: '2022-07-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 051',
        locationId: 3,
        departmentId: 18,
        startDate: '2021-09-01',
        endDate: '2022-07-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 052',
        locationId: 1,
        departmentId: 6,
        startDate: '2021-01-03',
        endDate: '2022-12-12',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 053',
        locationId: 1,
        departmentId: 19,
        startDate: '2022-06-01',
        endDate: '2022-12-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 054',
        locationId: 3,
        departmentId: 6,
        startDate: '2022-01-01',
        endDate: '2022-07-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 055',
        locationId: 2,
        departmentId: 5,
        startDate: '2021-09-01',
        endDate: '2022-04-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 056',
        locationId: 2,
        departmentId: 9,
        startDate: '2022-05-01',
        endDate: '2022-10-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 057',
        locationId: 2,
        departmentId: 11,
        startDate: '2021-09-01',
        endDate: '2022-12-31',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 058',
        locationId: 1,
        departmentId: 14,
        startDate: '2022-03-01',
        endDate: '2022-08-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 059',
        locationId: 1,
        departmentId: 18,
        startDate: '2022-01-01',
        endDate: '2022-07-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 061',
        locationId: 3,
        departmentId: 11,
        startDate: '2021-09-20',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 062',
        locationId: 3,
        departmentId: 20,
        startDate: '2021-09-14',
        endDate: '2022-12-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 064',
        locationId: 3,
        departmentId: 3,
        startDate: '2020-09-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 066',
        locationId: 1,
        departmentId: 11,
        startDate: '2022-01-10',
        endDate: '2022-12-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 071',
        locationId: 1,
        departmentId: 2,
        startDate: '2022-01-01',
        endDate: '2022-09-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 073',
        locationId: 3,
        departmentId: 21,
        startDate: '2021-12-28',
        endDate: '2022-06-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 074',
        locationId: 1,
        departmentId: 9,
        startDate: '2021-09-01',
        endDate: '2022-07-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 075',
        locationId: 1,
        departmentId: 3,
        startDate: '2022-05-01',
        endDate: '2022-09-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 077',
        locationId: 1,
        departmentId: 19,
        startDate: '2021-09-13',
        endDate: '2022-09-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 079',
        locationId: 1,
        departmentId: 11,
        startDate: '2022-01-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 080',
        locationId: 2,
        departmentId: 7,
        startDate: '2021-09-08',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 081',
        locationId: 2,
        departmentId: 22,
        startDate: '2020-09-01',
        endDate: '2023-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 082',
        locationId: 2,
        departmentId: 5,
        startDate: '2021-09-11',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 083',
        locationId: 1,
        departmentId: 14,
        startDate: '2022-01-01',
        endDate: '2022-05-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 087',
        locationId: 1,
        departmentId: 9,
        startDate: '2022-01-01',
        endDate: '2022-09-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 089',
        locationId: 1,
        departmentId: 23,
        startDate: '2021-09-02',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 091',
        locationId: 2,
        departmentId: 14,
        startDate: '2022-07-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 094',
        locationId: 2,
        departmentId: 5,
        startDate: '2022-01-01',
        endDate: '2022-07-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 095',
        locationId: 2,
        departmentId: 24,
        startDate: '2022-07-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 097',
        locationId: 1,
        departmentId: 3,
        startDate: '2022-06-01',
        endDate: '2022-12-31',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 098',
        locationId: 1,
        departmentId: 11,
        startDate: '2022-01-01',
        endDate: '2022-06-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 099',
        locationId: 3,
        departmentId: 3,
        startDate: '2022-07-30',
        endDate: '2022-12-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 100',
        locationId: 1,
        departmentId: 25,
        startDate: '2021-11-12',
        endDate: '2022-07-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 101',
        locationId: 1,
        departmentId: 14,
        startDate: '2021-09-14',
        endDate: '2023-07-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 102',
        locationId: 1,
        departmentId: 14,
        startDate: '2022-01-01',
        endDate: '2022-08-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 103',
        locationId: 2,
        departmentId: 18,
        startDate: '2022-08-30',
        endDate: '2022-12-31',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 105',
        locationId: 1,
        departmentId: 4,
        startDate: '2022-10-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 109',
        locationId: 1,
        departmentId: 14,
        startDate: '2022-01-01',
        endDate: '2022-06-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 110',
        locationId: 2,
        departmentId: 14,
        startDate: '2022-02-01',
        endDate: '2022-07-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 111',
        locationId: 1,
        departmentId: 14,
        startDate: '2022-01-01',
        endDate: '2022-06-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 112',
        locationId: 2,
        departmentId: 14,
        startDate: '2022-08-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 113',
        locationId: 1,
        departmentId: 14,
        startDate: '2022-08-01',
        endDate: '2022-12-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Projeto 115',
        locationId: 1,
        departmentId: 18,
        startDate: '2022-01-01',
        endDate: '2022-12-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Projects', null, {});
  },
};
